package com.pancc.learn.log.sl4j.migrate;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.log4j.LogManager;

import java.util.logging.Logger;

/**
 * @author Siweipancc
 */
public class MigrateSubLog {

    public static void mainRoute() {

        // 这里 JCL 应该被重定向
        Log log = LogFactory.getLog(MigrateSubLog.class);
        log.info(STR."This log is generated by \n[\{log.getClass()}] via \n[\{Log.class}]");

        // 这里 JUL 应该被重定向
        Logger logger = Logger.getLogger(MigrateSubLog.class.getName());
        logger.info(STR."This log is generated by \n[\{logger.getClass()}] via \n[\{Logger.class}]");


        // 遗留代码, 直接使用 log4j1
        org.apache.log4j.Logger logger1 = LogManager.getLogger(MigrateSubLog.class);
        logger1.info(STR."This log is generated by \n[\{logger1.getClass()}] via \n[\{org.apache.log4j.Logger.class}]");
    }
}
